#!/bin/bash


awslocal sqs list-queues

set -e

echo "[init] Verificando se a fila já existe..."

if ! awslocal sqs get-queue-url --queue-name themachine > /dev/null 2>&1; then
  echo "[init] Criando fila SQS no LocalStack..."
  awslocal sqs create-queue --queue-name themachine
  awslocal sqs create-queue --queue-name gerar-insights
  awslocal sqs create-queue --queue-name gerar-insights

  echo "=============================================="
  echo "[init] Fila criada: themachine"
  echo "=============================================="

  echo ""
  echo "=============================================="
  echo " Criando tabela DynamoDB..."
  echo "=============================================="

else
  echo "[init] Fila já existe: themachine"
fi

TABLE_NAME="AtivosTable"

  aws dynamodb create-table \
    --table-name $TABLE_NAME \
    --attribute-definitions AttributeName=pk,AttributeType=S \
    --key-schema AttributeName=pk,KeyType=HASH \
    --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 \
    --endpoint-url $LOCALSTACK_ENDPOINT &>/dev/null


  if [ $? -eq 0 ]; then
    echo "✅ Tabela criada: $TABLE_NAME"
  else
    echo "ℹ️ Tabela já existe ou ocorreu outro aviso."
  fi



